version: '3'
services:
  main-app:
    build: ./main-app
    ports:
      - "5000:5000"
    depends_on:
      db
  recommend-service:
    build: ./recommend-service
    ports:
      - "5002:5000"
  db:
    image: postgres:13
  pgadmin:
    image: pgadmin
    depends_on:
       - db
    ports:
      - "8080:80"



